/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_cpp_AppActivity */

#ifndef _Included_org_cocos2dx_cpp_AppActivity
#define _Included_org_cocos2dx_cpp_AppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_cpp_AppActivity
 * Method:    startGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_startGame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
